### ISSUE TITLE
Chat is vulnerable to XSS Attacks

### ISSUE THREAD

**Issue by Zeeraa** [SFSU-CSC-667/term-project-spring-2017-go#5]
You can can run javascript for all users by typing `<script>alert(0);</script>` in the chat (A XSS Attack) and this could be used to run any scrip you want in the users browser.

To fix this you could use `message = message.replace("<", "&lt;").replace(">", "&gt;"));` on the server side

**Comment by bopandrade** [comment]
thanks. i fixed it by using a more aggressive replacement.

**Comment by bopandrade** [comment]
it is still possible to use the same attack by changing your name to a malicious code. I will fix it by the end of the day.
